### ISSUE TITLE
Match Zendesk header to rest of site

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters-zendesk-theme#12]
The Zendesk header should match the header from the rest of the MicroMasters site a little better. 

#### Acceptance Criteria:

- [ ] Match the red background of the header. Should be `#a31f34`
- [ ] MIT and MITx Micromaster Programs in upper left should match
- [ ] Ideally the layout would be the same with the margins on the left and right sides matching (push out further to the sides)

MicroMasters Site Header
![image](https://user-images.githubusercontent.com/21342568/110037802-ea5d6180-7d0c-11eb-8cc3-1c91cb100931.png)

Zendesk Header
![image](https://user-images.githubusercontent.com/21342568/110037854-fd703180-7d0c-11eb-9334-a6d0750d53b6.png)

**Comment by briangrossman** [comment]
@arslanashraf7 
Looks good to me. Looks pretty much the same.

**Comment by arslanashraf7** [comment]
Closing, Associated PR is merged & deployed.
