### ISSUE TITLE
Match footer to Micromasters Site

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters-zendesk-theme#5]
The footer in the Zendesk pages should match the footer on the rest of the MicroMasters site. 

You can reference the [Zendesk theme in xPRO](https://github.com/mitodl/mitxpro-zendesk-theme).

![image](https://user-images.githubusercontent.com/21342568/108088831-e65fed00-7046-11eb-971f-c2afd4ee81c7.png)

**Comment by arslanashraf7** [comment]
@briangrossman just a quick question, Do we need to show the social media ticker on the Zendesk footer as seen [here](https://micromasters.mit.edu/)?

Screenshot: 
<img width="554" alt="Screenshot 2021-02-17 at 6 32 13 PM" src="https://user-images.githubusercontent.com/34372316/108211602-b3a11c00-714e-11eb-8bbf-f336b4fa1337.png">

**Comment by briangrossman** [comment]
@arslanashraf7 
Actually... I look around the MM site. I think that ticker should be included. The goal is to make the footer of the Zendesk pages to be the same as the rest of the site. Hopefully that's a reasonable request.
