### ISSUE TITLE
Add Contact Us link to footer

### ISSUE THREAD

**Issue by briangrossman** [mitodl/micromasters-zendesk-theme#6]
Similar to xPRO, please add a line that says: 
`Can't find what you're looking for? Contact Us` 

to the bottom of the Zendesk pages. It should behave like the Contact Us link in the footer of the rest of the MM pages.

![image](https://user-images.githubusercontent.com/21342568/108090666-dea14800-7048-11eb-9f4a-54994cfe0ed9.png)

You can use the [xPRO Zendesk theme](https://github.com/mitodl/mitxpro-zendesk-theme) for reference.

**Comment by arslanashraf7** [comment]
@briangrossman , Will we use the same background for this in MM as xPRO, as can be seen in the image attached to this issue's description?

**Comment by pdpinch** [comment]
No background please, since that is specific to the xPRO site. When you have a screenshot, we can ask @abdulkdawson for input, but my preference would be to keep this as simple as possible.

**Comment by briangrossman** [comment]
@arslanashraf7 
Adding on to what Peter said... here's a quick mock-up from Abdul:

![image](https://user-images.githubusercontent.com/21342568/108233152-7d917700-7111-11eb-8820-f094202885bc.png)

Horizontal Rule above Contact Us

Black Text: 
- font-family: Roboto
- color: black
- centered

Contact Us Button:
- font-family: Roboto
- color: white (font)
- background color: same blue from elsewhere on site: (#126f9a, I think)
- centered

**Comment by arslanashraf7** [comment]
> Adding on to what Peter said... here's a quick mock-up from Abdul:

@briangrossman Thanks for sharing the details, I'll go with this design.
